version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: descope-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: descope
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: descope-backend
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres:5432/descope"
      JWT_SECRET: "dev-secret"
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    volumes:
      - .:/app

volumes:
  pgdata:
